name: Build Binary and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Release
        uses: softprops/action-gh-release@v2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from Git Ref
        id: extract_version
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed 's/refs\/tags\/v//')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Checkout frontend repository
        uses: actions/checkout@v4
        with:
          repository: "krau/remdit-web"
          path: "frontend"
          token: ${{ secrets.REMDIT_PAT }} # Personal Access Token with repo scope

      - name: Install frontend dependencies
        run: |
          cd frontend
          pnpm install

      - name: Build frontend
        run: |
          cd frontend
          pnpm run build

      - name: Copy frontend dist to webembed
        run: |
          # Remove existing files in webembed except embed.go and 404.html
          find webembed -type f ! -name 'embed.go' ! -name '404.html' -delete
          # Copy dist contents to webembed (without the dist folder itself)
          cp -r frontend/dist/* webembed/

      - name: Release Go Binary
        uses: wangyoucao577/go-release-action@v1
        with:
          pre_command: export CGO_ENABLED=0
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ldflags: -s -w
          binary_name: remdit-server
        env:
          VERSION: ${{ env.VERSION }}
